### ISSUE TITLE
IOL links

### ISSUE THREAD

**Issue by itmwiw** [srl-labs/clabernetes#186]
Hello,  

I’m trying to use Cisco IOL on Clabernetes, and I’m encountering the following error message:  
`Error: failed to lookup link "vswitch-Ethernet0/1": Link not found`  

Here’s the `links` section from my topology file:  

```yaml
links:
  - endpoints: [client1:eth1, vswitch:Ethernet0/1]
  - endpoints: [client2:eth1, vswitch:e0/2]
```

The `client1` and `client2` nodes run without any issues.  

However, when I run `ip link show` in the `vswitch` pod, I see this output:  

```
34: clab-d36d286e@clab-f55cea4f: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 9500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default
    link/ether aa:c1:ab:39:38:04 brd ff:ff:ff:ff:ff:ff
    altname vswitch-Ethernet0-1
```

Is it normal to have `altname vswitch-Ethernet0-1` instead of `vswitch-Ethernet0/1`?

**Comment by hellt** [comment]
m, I think we never documented the peculiar detail
since interfaces are inherently backed up by a k8s service, it needs to comply by the rules of the k8s service naming. Which is - rfc 1123 or something like this.

That's why the `/` is swapped with `-`... If you want to make it work use the `ethX` notation in your clab file

**Comment by itmwiw** [comment]
@hellt Do you mean something like this?  

```yaml
links:
  - endpoints: [client1:eth1, vswitch:eth1]
  - endpoints: [client2:eth1, vswitch:eth2]
```  

If so, I get the following error:  

```
Error: IOL Node "vswitch" has an interface named "" which doesn't match the required pattern. Interfaces should be defined contiguously and named as Ethernet<slot>/<port> or e<slot>/<port>, where <slot> is a number from 0-9 and <port> is a number from 0-3. Management interface Ethernet0/0 cannot be used.
```  

Or is there something else I need to add?
